// web-vuejs/src/components/upload-widget-dropzone.vue
<script setup lang="ts">
import { useUploadsStore } from '@/store/uploads'
import { ref } from 'vue'

const addUploads = useUploadsStore().addUploads

const isDragging = ref(false)
const fileInputRef = ref<HTMLInputElement | null>(null)

function openFileDialog() {
  fileInputRef.value?.click()
}

function onDragOver(event: globalThis.DragEvent) {
  event.preventDefault()
  isDragging.value = true
}

function onDragLeave() {
  isDragging.value = false
}

function onDrop(event: globalThis.DragEvent) {
  event.preventDefault()
  isDragging.value = false

  if (event.dataTransfer?.files?.length) {
    const droppedFiles = Array.from(event.dataTransfer.files).filter(file =>
      file.type.startsWith('image/')
    )
    addUploads(droppedFiles)
  }
}

function onFileChange(newFiles: File[] | undefined) {
  if (newFiles?.length) {
    addUploads(newFiles)
  }
}
</script>

<template>
  <div class="d-flex flex-column px-3">
    <v-sheet
      class="d-flex flex-column align-center justify-center text-center text-zinc400" 
      width="100%"
      rounded="lg"
      elevation="2"
      :style="{
        border: '1px dashed' + (isDragging ? '#615fff' : '#3f3f46'),
        backgroundColor: isDragging ? 'rgba(25, 118, 210, 0.08)' : 'rgba(0, 0, 0, 0.20)',
        transition: 'all 0.2s ease',
        cursor: 'pointer',
        height: '8rem'
      }"
      @dragover="onDragOver"
      @dragleave="onDragLeave"
      @drop="onDrop"
      role="button"
      tabindex="0"
      @click="openFileDialog"
    >
      <span class="text-caption">Drop your files here or</span>
      <span class="text-decoration-underline text-caption">click to open picker</span>

      <!-- Input real escondido -->
      <input
        type="file"
        accept="image/*"
        multiple
        style="display: none"
        ref="fileInputRef"
        @change="onFileChange(Array.from(($event.target as HTMLInputElement).files || []))"
      />
    </v-sheet>

    <span class="text-caption text-zinc400 mt-2">Only PNG and JPG files are supported.</span>
  </div>
</template>

// web/src/components/upload-widget-dropzone.tsx
import { motion } from 'motion/react'
import { useDropzone } from "react-dropzone"
import { CircularProgressBar } from "./ui/circular-progress-bar"
import { useUploads } from '../store/uploads'

export function UploadWidgetDropzone() {
  const { addUploads } = useUploads();

  const isThereAnyPendingUpload = false
  const uploadGlobalPercentage = 66

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    multiple: true,
    accept: {
      'image/jpeg': [],
      'image/png': [],
    },
    onDrop(acceptedFiles) {
      addUploads(acceptedFiles)
    }
  })

  return (
    <motion.div
      className="px-3 flex flex-col gap-3"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
    >
      <div
        data-active={isDragActive}
        className="cursor-pointer text-zinc-400 bg-black/20 p-5 rounded-lg border border-zinc-700 border-dashed h-32 flex flex-col items-center justify-center gap-1 hover:border-zinc-600 transition-colors data-[active=true]:bg-indigo-500/10 data-[active=true]:border-indigo-500 data-[active=true]:text-indigo-400" {...getRootProps()}
      >
        <input type="file" {...getInputProps()} />

        {isThereAnyPendingUpload ? (
          <div className="flex flex-col gap-2.5 items-center">
            <CircularProgressBar progress={uploadGlobalPercentage} size={56} strokeWidth={4} />
            <span className="text-xs">Uploading 2 files...</span>
          </div>
        ) : (
          <>
            <span className="text-xs">Drop your files here or</span>
            <span className="text-xs underline">click to open picker</span>
          </>
        )}
      </div>

      <span className="text-xxs text-zinc-400">Only PNG and JPG files are supported.</span>
    </motion.div>
  )
}
