// web-vuejs/src/components/upload-widget-upload-item.vue
<script setup lang="ts">
  import { Icon } from '@iconify/vue'
  import { useUploadsStore, type Upload } from '@/store/uploads'
  import { formatBytes } from '@/utils/format-bytes';
  import { computed } from 'vue';

  const retryUpload = useUploadsStore().retryUpload
  const cancelUpload = useUploadsStore().cancelUpload

  const progress = computed(() => {
    return Math.min(
      props.upload.compressedSizeInBytes
        ? Math.round((props.upload.uploadSizeInBytes * 100) / props.upload.compressedSizeInBytes)
        : 0,
      100
    )
  })
  const compressedPercentage = computed(() => {
    if(!props.upload.compressedSizeInBytes) return 0
    return Math.round(((props.upload.originalSizeInBytes - props.upload.compressedSizeInBytes) * 100) / props.upload.originalSizeInBytes)
  })
  const progressColor = computed(() => {
    if(props.upload.status === 'success') return 'green400'
    if(props.upload.status === 'error') return 'red400'
    if(props.upload.status === 'cancelled') return 'yellow400'
    return 'indigo500'
  })
  
  interface Props {
    upload: Upload & { id: string }
  }

  const props = defineProps<Props>()
</script>

<template>
  <div 
    class="pa-3 rounded-lg d-flex flex-column ga-3 position-relative"
    style="background-color: rgba(255, 255, 255, 0.02);"
  >
    <div class="d-flex flex-column ga-1">
      <span class="text-caption font-weight-medium d-flex align-center ga-1">
        <Icon icon="mage:image-upload" color="#9f9fa9" height="16px" />
        <span>{{ props.upload.name }}</span>
      </span>

      <span class="text-zinc400 d-flex ga-1 align-center" style="font-size: 0.625rem">
        <span class="text-decoration-line-through">{{ formatBytes(props.upload.originalSizeInBytes) }}</span>
        <div style="width: 4px; height: 4px" class="rounded bg-zinc700"></div>
        <span>
          {{ formatBytes(props.upload.compressedSizeInBytes || 0) }}
          <span v-if="props.upload.compressedSizeInBytes" class="text-green400 ml-1">
            -{{ compressedPercentage }}%
          </span>
        </span>
        <div style="width: 4px; height: 4px" class="rounded bg-zinc700"></div>
        <span v-if="props.upload.status === 'success'">100%</span>
        <span v-if="props.upload.status === 'progress'">{{ progress }}%</span>
        <span v-if="props.upload.status === 'error'" class="text-red400">Error</span>
        <span v-if="props.upload.status === 'cancelled'" class="text-yellow400">Cancelled</span>
      </span>
    </div>

    <v-progress-linear
      bg-color="zinc800"
      :color="progressColor"
      :model-value="props.upload.status === 'progress' ? progress : 100"
      rounded
    ></v-progress-linear>

    <div class="position-absolute d-flex align-center ga-1" style="top: 0.625rem; right: 0.625rem;">
      <v-btn style="width: 1.5rem; height: 1.5rem" icon variant="text" class="d-flex flex-row align-center">
        <Icon icon="cuida:download-outline" color="#9f9fa9" height="16px" />
      </v-btn>

      <v-btn style="width: 1.5rem; height: 1.5rem" icon variant="text" class="d-flex flex-row align-center">
        <Icon icon="iconamoon:link" color="#9f9fa9" height="16px" />
      </v-btn>

      <v-btn @click="retryUpload(props.upload.id)" style="width: 1.5rem; height: 1.5rem" icon variant="text" class="d-flex flex-row align-center">
        <Icon icon="pepicons-pop:refresh" color="#9f9fa9" height="16px" />
      </v-btn>

      <v-btn @click="cancelUpload(props.upload.id)" style="width: 1.5rem; height: 1.5rem" icon variant="text" class="d-flex flex-row align-center">
        <Icon icon="material-symbols:close-rounded" color="#9f9fa9" height="16px" />
      </v-btn>
    </div>

  </div>
</template>

// web/src/components/upload-widget-upload-item.tsx
import { motion } from 'motion/react'
import * as Progress from "@radix-ui/react-progress";
import { Download, ImageUp, Link2, RefreshCcw, X } from "lucide-react";
import { Button } from "./ui/button";
import { useUploads, type Upload } from '../store/uploads';
import { formatBytes } from '../utils/format-bytes';
import { downloadUrl } from '../utils/download-url';

interface UploadWidgetUploadItemProps {
  upload: Upload
  uploadId: string
}

export function UploadWidgetUploadItem({ upload, uploadId }: UploadWidgetUploadItemProps) {
  const cancelUpload = useUploads(store => store.cancelUpload);
  const retryUpload = useUploads(store => store.retryUpload);

  const progress = Math.min(
    upload.compressedSizeInBytes
      ? Math.round((upload.uploadSizeInBytes * 100) / upload.compressedSizeInBytes)
      : 0,
    100
  )

  return (
    <motion.div
      className="p-3 rounded-lg flex flex-col gap-3 shadow-shape-content bg-white/[0.02] relative overflow-hidden"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.6 }}
    >
      <div className="flex flex-col gap-1">
        <span className="text-xs font-medium flex items-center gap-1">
          <ImageUp className="size-3 text-zinc-300" strokeWidth={1.5} />
          <span>{upload.name}</span>
        </span>

        <span className="text-xxs text-zinc-400 flex gap-1.5 items-center">
          <span className="line-through">{formatBytes(upload.originalSizeInBytes)}</span>
          <div className="size-1 rounded-full bg-zinc-700" />
          <span>
            {formatBytes(upload.compressedSizeInBytes || 0)}
            {upload.compressedSizeInBytes && (
              <span className="text-green-400 ml-1">
                -{Math.round(((upload.originalSizeInBytes - upload.compressedSizeInBytes) * 100) / upload.originalSizeInBytes)}%
              </span>
            )}
          </span>
          <div className="size-1 rounded-full bg-zinc-700" />
          {upload.status === 'success' && <span>100%</span>}
          {upload.status === 'progress' && <span>{progress}%</span>}
          {upload.status === 'error' && <span className='text-red-400'>Error</span>}
          {upload.status === 'cancelled' && <span className='text-yellow-400'>Cancelled</span>}
        </span>
      </div>

      <Progress.Root
        value={progress}
        data-status={upload.status}
        className="group bg-zinc-800 h-1 rounded-full overflow-hidden transition-all"
      >
        <Progress.Indicator
          className="bg-indigo-500 h-1 group-data-[status=success]:bg-green-400 group-data-[status=error]:bg-red-400 group-data-[status=cancelled]:bg-yellow-400"
          style={{ width: upload.status === 'progress' ? `${progress}%` : '100%' }}
        />
      </Progress.Root>

      <div className="absolute top-2.5 right-2.5 flex items-center gap-1">
        <Button
          aria-disabled={upload.status !== 'success'}
          size="icon-sm"
          onClick={() => upload.remoteUrl && downloadUrl(upload.remoteUrl)}
        >
          <Download className="size-4" strokeWidth={1.5} />
          <span className="sr-only">Download compressed image</span>
        </Button>

        <Button
          disabled={!upload.remoteUrl}
          size="icon-sm"
          onClick={() => upload.remoteUrl && navigator.clipboard.writeText(upload.remoteUrl!)}
        >
          <Link2 className="size-4" strokeWidth={1.5} />
          <span className="sr-only">Copy remote URL</span>
        </Button>

        <Button
          disabled={!['cancelled', 'error'].includes(upload.status)}
          size="icon-sm"
          onClick={() => retryUpload(uploadId)}
        >
          <RefreshCcw className="size-4" strokeWidth={1.5} />
          <span className="sr-only">Retry upload</span>
        </Button>

        <Button
          disabled={upload.status !== 'progress'}
          size="icon-sm"
          onClick={() => cancelUpload(uploadId)}
        >
          <X className="size-4" strokeWidth={1.5} />
          <span className="sr-only">Cancel upload</span>
        </Button>
      </div>
    </motion.div>
  )
}
