// web-vuejs/src/components/upload-widget-upload-list.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useUploadsStore } from '@/store/uploads';

  const uploadsMap = useUploadsStore().uploads
  const isUploadListEmpty = computed(() => uploadsMap.size === 0)

  const uploads = computed(() =>
    Array.from(uploadsMap.entries()).map(([id, upload]) => ({
      id,
      ...upload,
    }))
  )
</script>

<template>
  <div class="px-3 d-flex flex-column ga-3">
    <span class="font-weight-medium text-caption">
      Uploaded files <span class="text-zinc400">({{ uploadsMap.size }})</span>
    </span>

    <span v-if="isUploadListEmpty === true" class="text-zinc400 text-caption">No uploads added</span>
  
    <div v-if="isUploadListEmpty === false" v-for="upload in uploads" :key="upload.id">
      <UploadWidgetUploadItem :upload="upload" />
    </div>
  </div>
</template>

// web/src/components/upload-widget-upload-list.tsx
import { useUploads } from "../store/uploads";
import { UploadWidgetUploadItem } from "./upload-widget-upload-item";

export function UploadWidgetUploadList() {
  const uploads = useUploads(store => store.uploads);
  const isUploadListEmpty = uploads.size === 0

  return (
    <div className="px-3 flex flex-col gap-3">
      <span className="text-xs font-medium">Uploaded files{' '}
        <span className="text-zinc-400">(2)</span>
      </span>

      {isUploadListEmpty ? (
        <span className="text-xs text-zinc-400">No uploads added</span>
      ) : (
        <div className="space-y-2">
          {Array.from(uploads.entries()).map(([uploadId, upload]) => {
            return <UploadWidgetUploadItem key={uploadId} upload={upload} uploadId={uploadId} />
          })}
        </div>
      )}
    </div>
  )
}
