// web-vuejs/src/components/upload-widget.vue
<script setup lang="ts">
  import { motion, VariantType } from 'motion-v';
  import { ref } from 'vue';
  import { CollapsibleContent, CollapsibleRoot } from 'reka-ui'
  import UploadWidgetHeader from '@/components/upload-widget-header.vue';
  import UploadWidgetDropzone from '@/components/upload-widget-dropzone.vue';
  import UploadWidgetUploadList from '@/components/upload-widget-upload-list.vue';


  const widgetOpen = ref(false)

  const variants: Record<string, VariantType> = {
    closed: {
      width: 'max-content',
      height: '44px',
      transition: {
        type: 'tween'
      }
    },
    open: {
      width: '360px',
      height: 'auto',
      transition: {
        duration: 0.2
      }
    }
  }
</script>

<template>
  <CollapsibleRoot v-model:open="widgetOpen" asChild>
    <motion.div 
      style="width: 100%; max-width: 360px;" 
      class="d-flex bg-zinc900 flex-column overflow-hidden"
      :class="widgetOpen ? 'rounded-lg' : 'rounded-xl'"
      :initial="false"
      :animate="widgetOpen ? 'open' : 'closed'"
      :variants="variants"
    >
      <UploadWidgetMinimizedButton v-if="!widgetOpen" />

      <CollapsibleContent>
        <UploadWidgetHeader />

        <div class="d-flex flex-column ga-4 py-3">
          <UploadWidgetDropzone />

          <v-divider color="zinc500" />

          <UploadWidgetUploadList />
        </div>
      </CollapsibleContent>
    </motion.div>
  </CollapsibleRoot>
</template>

// web/src/components/upload-widget.tsx
import * as Collapsible from "@radix-ui/react-collapsible";
import { UploadWidgetDropzone } from "./upload-widget-dropzone";
import { UploadWidgetHeader } from "./upload-widget-header";
import { UploadWidgetUploadList } from "./upload-widget-upload-list";
import { UploadWidgetMinimizedButton } from "./upload-widget-minimized-button";
import { motion, useCycle } from 'motion/react'
import { usePendingUploads } from "../store/uploads";

export function UploadWidget() {
  const { isThereAnyPendingUploads } = usePendingUploads();

  const [isWidgetOpen, toogleWidgetOpen] = useCycle(false, true)

  return (
    <Collapsible.Root onOpenChange={() => toogleWidgetOpen()} asChild>
      <motion.div
        data-progress={isThereAnyPendingUploads}
        className="bg-zinc-900 overflow-hidden max-w-[360px] rounded-xl data-[state=open]:shadow-shape border border-transparent animate-border data-[state=closed]:rounded-3xl data-[state=closed]:data-[progress=false]:shadow-shape data-[state=closed]:data-[progress=true]:[background:linear-gradient(45deg,#09090B,theme(colors.zinc.900)_50%,#09090B)_padding-box,conic-gradient(from_var(--border-angle),theme(colors.zinc.700/.48)_80%,_theme(colors.indigo.500)_86%,_theme(colors.indigo.300)_90%,_theme(colors.indigo.500)_94%,_theme(colors.zinc.600/.48))_border-box]"
        animate={isWidgetOpen ? 'open' : 'closed'}
        variants={{
          closed: {
            width: 'max-content',
            height: 44,
            transition: {
              type: 'tween'
            }
          },
          open: {
            width: 360,
            height: 'auto',
            transition: {
              duration: 0.2
            }
          }
        }}
      >
        {!isWidgetOpen && <UploadWidgetMinimizedButton />}

        <Collapsible.Content>
          <UploadWidgetHeader />

          <div className="flex flex-col gap-4 py-3">
            <UploadWidgetDropzone />

            <div className="h-px box-content bg-zinc-800 border-t border-black/50" />

            <UploadWidgetUploadList />
          </div>
        </Collapsible.Content>

      </motion.div>
    </Collapsible.Root>
  )
}
